name: tartarus
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  animated_splash_screen: ^1.3.0
  animated_text_kit: ^4.2.2
  animations: ^2.0.7
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_animation_progress_bar: ^2.3.1
  flutter_carousel_widget: ^2.0.1
  flutter_launcher_icons: ^0.11.0
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^0.22.0
  get: ^4.6.5
  get_storage: ^2.0.3
  google_fonts: ^2.1.0
  http: ^0.13.5
  lottie: ^2.1.0
  page_transition: ^2.0.9
  permission_handler: ^10.2.0
  responsive_sizer: ^3.1.1
  scroll_date_picker: ^3.6.1
  scroll_loop_auto_scroll: ^0.0.5
  shake: ^2.2.0
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  shimmer_animation: ^2.1.0+1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/MainLogo.png"
  adaptive_icon_background: "#170355"
  adaptive_icon_foreground: "assets/MainLogo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/astrology.png
    - assets/back.jpg
    - assets/splash.json
    - assets/google.png
    - assets/female.svg
    - assets/male.svg
    - assets/maleandfemale.svg
    - assets/Burclar/akrep.svg
    - assets/Burclar/aslan.svg
    - assets/Burclar/boga.svg
    - assets/Burclar/balik.svg
    - assets/Burclar/basak.svg
    - assets/Burclar/koc.svg
    - assets/Burclar/kova.svg
    - assets/Burclar/oglak.svg
    - assets/Burclar/terazi.svg
    - assets/Burclar/yay.svg
    - assets/Burclar/ikizler.svg
    - assets/Burclar/yengec.svg
    - assets/MainLogo.png
    - assets/pngMainLogo.png
    - assets/ProfiePic.svg
    - assets/arkascale.json
    - assets/donenkure.json
    - assets/settingnew.svg
    - assets/burcarkasi.json
    - assets/fallingmeteor.json
    - assets/femaleprofile.json
    - assets/maleprofile.json
    - assets/hand.json
    - assets/loadingcubuk.json
    - assets/baliklar.png
    - assets/kurabiyefali.png
    - assets/askfali.png
    - assets/gununfali.png
    - assets/tarotcard.png
    - assets/burcyorumu.png
    - assets/isimyorum.png
    - assets/location.svg
    - assets/procard.svg
    - assets/burcuyumu.png
    - assets/coininhand.svg
